### ISSUE TITLE
composer.json

### ISSUE THREAD

**Issue by mhauri** [Vinai/VinaiKopp_StoreUrlRewrites#4]
Hi Vinai, could you please add a composer.json file, so it is possible to install the extension with Composer?

Thx and Cheers
Marcel

**Comment by Vinai** [comment]
This is just a small temporary fix extension for Magento 1.8 if I recall correctly. I'm not using it anywhere anymore at the moment.
Please feel free to send a PR, I'd be happy to merge!

**Comment by andreasemer** [comment]
Here https://github.com/Vinai/VinaiKopp_StoreUrlRewrites/pull/9 you can find the PR... :-)

**Comment by Vinai** [comment]
Thank you!
